[theme]
primaryColor = "#059669"
backgroundColor = "#f6fbf8"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f291e"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
